---
- name: Set mysql password
  command: ./bin/config set mysql.pass {{ mysql_root_password }}
  args:
    chdir: "{{ phabricator_install_directory }}"

- name: Initialize database storage (use --force for noninteractive version)
  command: ./bin/storage upgrade --force
  args:
    chdir: "{{ phabricator_install_directory }}"